version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: ts-node-dev
    versions:
    - 1.1.1
    - 1.1.3
  - dependency-name: uuidv4
    versions:
    - 6.2.6
  - dependency-name: pg
    versions:
    - 8.5.1
  - dependency-name: eslint-import-resolver-typescript
    versions:
    - 2.3.0
  - dependency-name: lodash
    versions:
    - 4.17.20
